---
version: "3.9"

networks:
  host:
    name: host
    external: true
  alpha:
    name: alpha
    attachable: true
  beta:
    name: beta
    attachable: true

services:
  ratcouncil:
    image: firecow/ratnation:${DOCKER_TAG:-latest}
    networks: [host]
    command: council --port 8080
    ports:
      - { target: 8080, published: 8080, protocol: tcp, mode: host }

  ratking1:
    image: firecow/ratnation:${DOCKER_TAG:-latest}
    networks: [host]
    command:
      king
      --council-host="http://$DOCKER_SWARN_NODE_IP:8080"
      --host="$DOCKER_SWARN_NODE_IP"
      --rathole="bind_port=2333 ports=5000-5001"
    ports:
      - { target: 2333, published: 2333, protocol: tcp, mode: host }
      - { target: 5000, published: 5000, protocol: tcp, mode: host }
      - { target: 5001, published: 5001, protocol: tcp, mode: host }

  ratking2:
    image: firecow/ratnation:${DOCKER_TAG:-latest}
    networks: [host]
    command:
      king
      --council-host="http://$DOCKER_SWARN_NODE_IP:8080"
      --host="$DOCKER_SWARN_NODE_IP"
      --rathole="bind_port=2334 ports=5002-5003"
      --rathole="bind_port=2335 ports=5004-5004"
    ports:
      - { target: 2334, published: 2334, protocol: tcp, mode: host }
      - { target: 2335, published: 2335, protocol: tcp, mode: host }
      - { target: 5002, published: 5002, protocol: tcp, mode: host }
      - { target: 5003, published: 5003, protocol: tcp, mode: host }
      - { target: 5004, published: 5004, protocol: tcp, mode: host }

  # Alpha stack/pod
  ratling-alpha:
    image: firecow/ratnation:${DOCKER_TAG:-latest}
    networks: [alpha]
    # ports:
    #   - { published: 2183, target: 2183, protocol: tcp, mode: host }
    command:
      ling
      --council-host="http://$DOCKER_SWARN_NODE_IP:8080"
      --rathole="name=alpha local_addr=echoserver-alpha:8080"
      --socat="name=beta bind_port=2183"
  echoserver-alpha:
    hostname: echoserver-alpha
    image: jmalloc/echo-server
    networks: [alpha]

  # Beta stack/pod
  ratling-beta:
    image: firecow/ratnation:${DOCKER_TAG:-latest}
    networks: [beta]
    ports:
      - { published: 2184, target: 2184, protocol: tcp, mode: host }
    command:
      ling
      --council-host="http://$DOCKER_SWARN_NODE_IP:8080"
      --rathole="name=beta local_addr=echoserver-beta:8080"
      --socat="name=alpha bind_port=2184"
  echoserver-beta:
    image: jmalloc/echo-server
    hostname: echoserver-beta
    networks: [beta]
