---
name: Quality Assurance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm run build
      - run: npm test
